import type { Locale } from "@/lib/i18n";

const ru = {
  meta: {
    title: "Nafis — натуральная косметика с доставкой по Ташкенту (демо)",
    description: "Демо интернет-магазина от CaravanHouse: каталог с фильтрами, быстрый просмотр, корзина с промокодом, оформление заказа и панель продавца.",
  },
  demo: { text: "Демо-магазин от CaravanHouse — бренд вымышленный, заказы и оплата не проводятся.", cta: "Заказать такой магазин" },
  nav: { catalog: "Каталог", hits: "Хиты", sets: "Наборы", delivery: "Доставка", admin: "Панель продавца" },
  langLabel: "Язык",
  search: "Найти средство…",
  currency: "сум",
  hero: {
    eyebrow: "Новая коллекция · осень",
    title: "Уход, который",
    titleAccent: "видно в зеркале",
    subtitle: "Натуральные формулы для климата Узбекистана. Доставим по Ташкенту сегодня, по регионам — за 2–4 дня.",
    cta: "Смотреть каталог",
    promo: "−20% на первый заказ по промокоду",
    perks: ["Доставка от 500 000 сум — бесплатно", "Пробники к каждому заказу", "Возврат 14 дней"],
  },
  categories: { all: "Все", face: "Лицо", body: "Тело", hair: "Волосы", lips: "Губы", sets: "Наборы" },
  skins: { dry: "Сухая", oily: "Жирная", normal: "Нормальная", sensitive: "Чувствительная" },
  catalog: {
    title: "Каталог",
    skin: "Тип кожи",
    price: "Цена до",
    sort: "Сортировка",
    sorts: { popular: "Популярные", cheap: "Сначала дешевле", expensive: "Сначала дороже", new: "Новинки" },
    found: "товаров",
    empty: "Ничего не нашли — попробуйте убрать фильтры",
    reset: "Сбросить фильтры",
    filters: "Фильтры",
    apply: "Показать",
  },
  badge: { hit: "Хит", new: "Новинка", sale: "Скидка" },
  product: {
    add: "В корзину",
    added: "В корзине",
    quick: "Быстрый просмотр",
    volume: "Объём",
    howTo: "Как применять",
    ingredients: "Ключевые компоненты",
    skin: "Подходит для кожи",
    close: "Закрыть",
    wish: "В избранное",
  },
  cart: {
    title: "Корзина",
    empty: "Корзина пуста",
    emptyHint: "Добавьте что-нибудь из каталога — например, хит продаж с витамином C.",
    toCatalog: "В каталог",
    subtotal: "Товары",
    discount: "Скидка по промокоду",
    delivery: "Доставка",
    total: "Итого",
    promo: "Промокод",
    apply: "Применить",
    promoOk: "Промокод применён: −20%",
    promoBad: "Такого промокода нет",
    promoHint: "Попробуйте DEMO20",
    freeLeft: "До бесплатной доставки",
    freeOk: "Доставка будет бесплатной 🎉",
    checkout: "Оформить заказ",
    remove: "Удалить",
    free: "бесплатно",
  },
  checkout: {
    title: "Оформление заказа",
    steps: ["Контакты", "Доставка", "Оплата"],
    name: "Имя",
    phone: "Телефон",
    address: "Адрес доставки",
    courier: "Курьером по Ташкенту",
    courierNote: "Сегодня, если заказать до 16:00",
    region: "В регионы Узбекистана",
    regionNote: "2–4 рабочих дня",
    pickup: "Самовывоз из шоурума",
    pickupNote: "Мирабадский район, демо-адрес",
    card: "Картой онлайн",
    cardNote: "В демо оплата не проводится",
    cash: "Наличными или картой курьеру",
    cashNote: "При получении",
    next: "Далее",
    back: "Назад",
    place: "Подтвердить заказ",
    required: "Заполните имя, телефон и адрес",
    successTitle: "Заказ оформлен!",
    successText: "Это демо: заказ сохранён только в вашем браузере. Откройте «Панель продавца», чтобы увидеть, как он выглядит для магазина.",
    order: "Заказ",
    toAdmin: "Открыть панель продавца",
    continue: "Продолжить покупки",
  },
  delivery: {
    title: "Доставка и оплата",
    items: [
      { title: "По Ташкенту", text: "Курьер в день заказа до 16:00, 25 000 сум. От 500 000 сум — бесплатно." },
      { title: "По Узбекистану", text: "Почтой и курьерскими службами за 2–4 дня, 45 000 сум." },
      { title: "Самовывоз", text: "Бесплатно из шоурума — заказ готов через 2 часа." },
      { title: "Оплата", text: "Картой онлайн или при получении. Чек приходит в Telegram." },
    ],
  },
  footer: { about: "Nafis — вымышленный бренд для демонстрации интернет-магазина.", made: "Магазин сделан командой CaravanHouse" },
  admin: {
    title: "Панель продавца",
    subtitle: "Так магазин видит заказы: статусы, сумма за день, состав. В настоящем проекте сюда же приходят уведомления в Telegram.",
    back: "← В магазин",
    today: "Заказы сегодня",
    revenue: "Выручка сегодня",
    avg: "Средний чек",
    newOrders: "Новые",
    order: "Заказ",
    customer: "Покупатель",
    items: "Состав",
    sum: "Сумма",
    status: "Статус",
    statuses: { new: "Новый", packing: "Собирается", shipping: "В пути", done: "Доставлен" },
    yours: "ваш",
    empty: "Заказов пока нет",
    reset: "Сбросить демо-заказы",
  },
};

export type UI = typeof ru;

const uz: UI = {
  meta: {
    title: "Nafis — Toshkent boʻylab yetkazib beriladigan tabiiy kosmetika (demo)",
    description: "CaravanHouse tayyorlagan internet-doʻkon demosi: filtrli katalog, tezkor koʻrish, promokodli savat, buyurtma berish va sotuvchi paneli.",
  },
  demo: { text: "CaravanHouse demo-doʻkoni — brend oʻylab topilgan, buyurtma va toʻlovlar amalga oshirilmaydi.", cta: "Shunday doʻkon buyurtma qilish" },
  nav: { catalog: "Katalog", hits: "Xitlar", sets: "Toʻplamlar", delivery: "Yetkazib berish", admin: "Sotuvchi paneli" },
  langLabel: "Til",
  search: "Vositani topish…",
  currency: "soʻm",
  hero: {
    eyebrow: "Yangi kolleksiya · kuz",
    title: "Koʻzguda",
    titleAccent: "koʻrinadigan parvarish",
    subtitle: "Oʻzbekiston iqlimi uchun tabiiy formulalar. Toshkent boʻylab bugun, viloyatlarga — 2–4 kunda yetkazamiz.",
    cta: "Katalogni koʻrish",
    promo: "Promokod bilan birinchi buyurtmaga −20%",
    perks: ["500 000 soʻmdan yetkazib berish — bepul", "Har bir buyurtmaga namunalar", "14 kun ichida qaytarish"],
  },
  categories: { all: "Hammasi", face: "Yuz", body: "Tana", hair: "Soch", lips: "Lab", sets: "Toʻplamlar" },
  skins: { dry: "Quruq", oily: "Yogʻli", normal: "Normal", sensitive: "Sezgir" },
  catalog: {
    title: "Katalog",
    skin: "Teri turi",
    price: "Narx gacha",
    sort: "Saralash",
    sorts: { popular: "Ommabop", cheap: "Avval arzonroq", expensive: "Avval qimmatroq", new: "Yangiliklar" },
    found: "ta mahsulot",
    empty: "Hech narsa topilmadi — filtrlarni olib tashlab koʻring",
    reset: "Filtrlarni tozalash",
    filters: "Filtrlar",
    apply: "Koʻrsatish",
  },
  badge: { hit: "Xit", new: "Yangi", sale: "Chegirma" },
  product: {
    add: "Savatga",
    added: "Savatda",
    quick: "Tezkor koʻrish",
    volume: "Hajm",
    howTo: "Qanday qoʻllash",
    ingredients: "Asosiy komponentlar",
    skin: "Mos teri turi",
    close: "Yopish",
    wish: "Sevimlilarga",
  },
  cart: {
    title: "Savat",
    empty: "Savat boʻsh",
    emptyHint: "Katalogdan biror narsa qoʻshing — masalan, C vitaminli xit mahsulot.",
    toCatalog: "Katalogga",
    subtotal: "Mahsulotlar",
    discount: "Promokod chegirmasi",
    delivery: "Yetkazib berish",
    total: "Jami",
    promo: "Promokod",
    apply: "Qoʻllash",
    promoOk: "Promokod qoʻllandi: −20%",
    promoBad: "Bunday promokod yoʻq",
    promoHint: "DEMO20 ni sinab koʻring",
    freeLeft: "Bepul yetkazib berishgacha",
    freeOk: "Yetkazib berish bepul boʻladi 🎉",
    checkout: "Buyurtma berish",
    remove: "Oʻchirish",
    free: "bepul",
  },
  checkout: {
    title: "Buyurtmani rasmiylashtirish",
    steps: ["Aloqa", "Yetkazib berish", "Toʻlov"],
    name: "Ism",
    phone: "Telefon",
    address: "Yetkazib berish manzili",
    courier: "Toshkent boʻylab kuryer",
    courierNote: "Soat 16:00 gacha buyurtma qilsangiz — bugun",
    region: "Oʻzbekiston viloyatlariga",
    regionNote: "2–4 ish kuni",
    pickup: "Shourumdan olib ketish",
    pickupNote: "Mirobod tumani, demo-manzil",
    card: "Onlayn karta orqali",
    cardNote: "Demoda toʻlov amalga oshirilmaydi",
    cash: "Kuryerga naqd yoki karta orqali",
    cashNote: "Qabul qilganda",
    next: "Keyingi",
    back: "Orqaga",
    place: "Buyurtmani tasdiqlash",
    required: "Ism, telefon va manzilni toʻldiring",
    successTitle: "Buyurtma qabul qilindi!",
    successText: "Bu demo: buyurtma faqat brauzeringizda saqlandi. Doʻkon uni qanday koʻrishini bilish uchun «Sotuvchi paneli»ni oching.",
    order: "Buyurtma",
    toAdmin: "Sotuvchi panelini ochish",
    continue: "Xaridni davom ettirish",
  },
  delivery: {
    title: "Yetkazib berish va toʻlov",
    items: [
      { title: "Toshkent boʻylab", text: "Soat 16:00 gacha buyurtma qilinsa — oʻsha kuni kuryer, 25 000 soʻm. 500 000 soʻmdan — bepul." },
      { title: "Oʻzbekiston boʻylab", text: "Pochta va kuryer xizmatlari orqali 2–4 kunda, 45 000 soʻm." },
      { title: "Olib ketish", text: "Shourumdan bepul — buyurtma 2 soatda tayyor." },
      { title: "Toʻlov", text: "Onlayn karta orqali yoki qabul qilganda. Chek Telegramga keladi." },
    ],
  },
  footer: { about: "Nafis — internet-doʻkonni namoyish qilish uchun oʻylab topilgan brend.", made: "Doʻkon CaravanHouse jamoasi tomonidan yaratilgan" },
  admin: {
    title: "Sotuvchi paneli",
    subtitle: "Doʻkon buyurtmalarni shunday koʻradi: holatlar, kunlik summa, tarkib. Haqiqiy loyihada bu yerga Telegram bildirishnomalari ham keladi.",
    back: "← Doʻkonga",
    today: "Bugungi buyurtmalar",
    revenue: "Bugungi tushum",
    avg: "Oʻrtacha chek",
    newOrders: "Yangi",
    order: "Buyurtma",
    customer: "Xaridor",
    items: "Tarkib",
    sum: "Summa",
    status: "Holat",
    statuses: { new: "Yangi", packing: "Yigʻilmoqda", shipping: "Yoʻlda", done: "Yetkazildi" },
    yours: "sizniki",
    empty: "Hozircha buyurtmalar yoʻq",
    reset: "Demo buyurtmalarni tiklash",
  },
};

const dictionaries: Record<Locale, UI> = { ru, uz };
export const getUI = (lang: Locale) => dictionaries[lang];
